[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth-*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200